ALTER TABLE report_drafts ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
UPDATE report_drafts
SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default')
WHERE tenant_id IS NULL;
ALTER TABLE report_drafts ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE report_drafts
    ADD CONSTRAINT fk_report_drafts_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
CREATE INDEX IF NOT EXISTS idx_report_drafts_tenant_generated_at
    ON report_drafts (tenant_id, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_knowledge_vector_store_tenant
    ON knowledge_vector_store ((metadata->>'tenantId'));

CREATE TABLE IF NOT EXISTS tenant_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    base_url VARCHAR(512) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    allowed_hosts VARCHAR(1024) NOT NULL,
    secret_ciphertext VARCHAR(2048) NOT NULL,
    secret_version INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_tenant_model_configs_tenant UNIQUE (tenant_id),
    CONSTRAINT fk_tenant_model_configs_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_model_configs_updated
    ON tenant_model_configs (tenant_id, updated_at);
