package com.brand.agentpoc.auth.domain;

public enum PermissionKey {
    USER_READ,
    USER_MANAGE,
    ROLE_READ,
    ROLE_MANAGE,
    ORGANIZATION_READ,
    ORGANIZATION_MANAGE,
    ORGANIZATION_GRANT_MANAGE,
    DASHBOARD_READ,
    DATA_READ,
    CHAT_USE,
    KNOWLEDGE_QUERY,
    REPORT_READ,
    REPORT_GENERATE,
    REPORT_COLLABORATE,
    MODEL_CONFIG_TEST,
    MODEL_USAGE_READ,
    MODEL_USAGE_MANAGE,
    MODEL_USAGE_PLATFORM_READ
}
