ALTER TABLE tenant_memberships ADD COLUMN email VARCHAR(254);

ALTER TABLE tenant_memberships ADD CONSTRAINT uq_tenant_memberships_tenant_email
    UNIQUE (tenant_id, email);

CREATE INDEX idx_tenant_memberships_tenant_email
    ON tenant_memberships (tenant_id, email);

CREATE TABLE tenant_smtp_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    security_mode VARCHAR(16) NOT NULL,
    username VARCHAR(254) NOT NULL,
    password_ciphertext VARCHAR(2048) NOT NULL,
    secret_version INTEGER NOT NULL,
    from_address VARCHAR(254) NOT NULL,
    from_display_name VARCHAR(128),
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_tenant_smtp_configs_tenant UNIQUE (tenant_id),
    CONSTRAINT ck_tenant_smtp_configs_security
        CHECK ((security_mode = 'STARTTLS' AND port = 587)
            OR (security_mode = 'SMTPS' AND port = 465)),
    CONSTRAINT fk_tenant_smtp_configs_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_tenant_smtp_configs_updated
    ON tenant_smtp_configs (tenant_id, updated_at);

CREATE TABLE report_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_job_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    creator_user_id BIGINT NOT NULL,
    report_draft_id VARCHAR(128) NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    channel_key VARCHAR(32) NOT NULL,
    delivery_key VARCHAR(192) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    error_code VARCHAR(64),
    provider_message_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_report_deliveries_job_channel_recipient
        UNIQUE (report_job_id, channel_key, recipient_user_id),
    CONSTRAINT uq_report_deliveries_key UNIQUE (delivery_key),
    CONSTRAINT fk_report_deliveries_job
        FOREIGN KEY (report_job_id) REFERENCES report_generation_jobs (id),
    CONSTRAINT fk_report_deliveries_subscription
        FOREIGN KEY (subscription_id) REFERENCES report_subscriptions (id),
    CONSTRAINT fk_report_deliveries_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_deliveries_creator
        FOREIGN KEY (creator_user_id) REFERENCES auth_users (id),
    CONSTRAINT fk_report_deliveries_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_deliveries_claim
    ON report_deliveries (status, next_retry_at, created_at, id);

CREATE INDEX idx_report_deliveries_tenant
    ON report_deliveries (tenant_id, creator_user_id, created_at, id);

CREATE INDEX idx_report_deliveries_job
    ON report_deliveries (report_job_id, recipient_user_id);
