INSERT INTO auth_role_permissions (role_id, permission_key)
SELECT role.id, 'REPORT_COLLABORATE'
FROM auth_roles role
WHERE role.role_key IN ('ADMIN', 'ANALYST')
  AND NOT EXISTS (
      SELECT 1
      FROM auth_role_permissions permission
      WHERE permission.role_id = role.id
        AND permission.permission_key = 'REPORT_COLLABORATE'
  );

CREATE TABLE report_collaborations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    report_draft_id VARCHAR(128) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id VARCHAR(2048) NOT NULL,
    status VARCHAR(32) NOT NULL,
    assignee_user_id BIGINT,
    assignee_username VARCHAR(128),
    assignee_display_name VARCHAR(128),
    activity_count BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_report_collaborations_report UNIQUE (tenant_id, report_draft_id),
    CONSTRAINT fk_report_collaborations_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_collaborations_assignee
        FOREIGN KEY (assignee_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_collaborations_filter
    ON report_collaborations (tenant_id, status, assignee_user_id, updated_at, id);

CREATE INDEX idx_report_collaborations_scope
    ON report_collaborations (tenant_id, scope_type, updated_at, id);

CREATE TABLE report_collaboration_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaboration_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    report_draft_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    actor_user_id BIGINT,
    actor_username VARCHAR(128) NOT NULL,
    actor_display_name VARCHAR(128) NOT NULL,
    previous_value VARCHAR(256),
    current_value VARCHAR(256),
    comment_body TEXT,
    trace_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_report_collaboration_events_collaboration
        FOREIGN KEY (collaboration_id) REFERENCES report_collaborations (id),
    CONSTRAINT fk_report_collaboration_events_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_collaboration_events_actor
        FOREIGN KEY (actor_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_collaboration_events_timeline
    ON report_collaboration_events (tenant_id, report_draft_id, created_at, id);

CREATE TABLE report_collaboration_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaboration_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    channel_key VARCHAR(32) NOT NULL,
    delivery_key VARCHAR(192) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    error_code VARCHAR(64),
    provider_message_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_report_collaboration_notifications_event_recipient
        UNIQUE (event_id, recipient_user_id),
    CONSTRAINT uq_report_collaboration_notifications_key UNIQUE (delivery_key),
    CONSTRAINT fk_report_collaboration_notifications_collaboration
        FOREIGN KEY (collaboration_id) REFERENCES report_collaborations (id),
    CONSTRAINT fk_report_collaboration_notifications_event
        FOREIGN KEY (event_id) REFERENCES report_collaboration_events (id),
    CONSTRAINT fk_report_collaboration_notifications_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_collaboration_notifications_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_collaboration_notifications_claim
    ON report_collaboration_notifications (status, next_retry_at, created_at, id);

CREATE INDEX idx_report_collaboration_notifications_tenant
    ON report_collaboration_notifications (tenant_id, created_at, id);
