INSERT INTO auth_role_permissions (role_id, permission_key)
SELECT role.id, permission.permission_key
FROM auth_roles role
CROSS JOIN (
    SELECT 'MODEL_USAGE_READ' AS permission_key
    UNION ALL SELECT 'MODEL_USAGE_MANAGE'
    UNION ALL SELECT 'MODEL_USAGE_PLATFORM_READ'
) permission
WHERE role.role_key = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1
      FROM auth_role_permissions existing
      WHERE existing.role_id = role.id
        AND existing.permission_key = permission.permission_key
  );

CREATE TABLE model_price_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    provider_key VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    version_key VARCHAR(128) NOT NULL,
    input_price_per_million DECIMAL(20,8) NOT NULL,
    output_price_per_million DECIMAL(20,8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    source VARCHAR(64) NOT NULL,
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_model_price_versions_key UNIQUE (tenant_id, version_key),
    CONSTRAINT fk_model_price_versions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_model_price_versions_creator FOREIGN KEY (created_by) REFERENCES auth_users (id)
);

CREATE INDEX idx_model_price_versions_lookup
    ON model_price_versions (tenant_id, provider_key, model_name, effective_from, id);

CREATE TABLE model_budget_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    monthly_limit DECIMAL(20,8) NOT NULL,
    soft_threshold_percent INTEGER NOT NULL,
    hard_limit_enabled BOOLEAN NOT NULL,
    fail_open BOOLEAN NOT NULL,
    reservation_amount DECIMAL(20,8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_model_budget_policies_tenant UNIQUE (tenant_id),
    CONSTRAINT ck_model_budget_policies_amounts CHECK (
        monthly_limit > 0 AND reservation_amount >= 0
    ),
    CONSTRAINT ck_model_budget_policies_threshold CHECK (
        soft_threshold_percent BETWEEN 1 AND 100
    ),
    CONSTRAINT fk_model_budget_policies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_model_budget_policies_updated
    ON model_budget_policies (tenant_id, updated_at);

CREATE TABLE model_budget_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_key VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    amount DECIMAL(20,8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_model_budget_reservations_call UNIQUE (call_key),
    CONSTRAINT fk_model_budget_reservations_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_model_budget_reservations_active
    ON model_budget_reservations (tenant_id, status, expires_at, id);

CREATE TABLE model_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_key VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT,
    provider_key VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    scenario VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    token_state VARCHAR(16) NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    total_tokens BIGINT,
    duration_ms BIGINT NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    cache_hit BOOLEAN NOT NULL,
    price_version_id BIGINT,
    price_version_key VARCHAR(128),
    input_price_per_million DECIMAL(20,8),
    output_price_per_million DECIMAL(20,8),
    estimated_cost DECIMAL(20,8),
    currency VARCHAR(3),
    cost_source VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_model_usage_events_call UNIQUE (call_key),
    CONSTRAINT fk_model_usage_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_model_usage_events_user FOREIGN KEY (user_id) REFERENCES auth_users (id),
    CONSTRAINT fk_model_usage_events_price FOREIGN KEY (price_version_id) REFERENCES model_price_versions (id)
);

CREATE INDEX idx_model_usage_events_tenant_time
    ON model_usage_events (tenant_id, occurred_at, id);
CREATE INDEX idx_model_usage_events_scenario
    ON model_usage_events (tenant_id, scenario, occurred_at);
CREATE INDEX idx_model_usage_events_model
    ON model_usage_events (tenant_id, provider_key, model_name, occurred_at);
