CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_key VARCHAR(64) NOT NULL,
    source VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id VARCHAR(128),
    active BOOLEAN NOT NULL,
    fallback_active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    activated_at TIMESTAMP WITH TIME ZONE,
    message VARCHAR(512) NOT NULL,
    CONSTRAINT uq_import_batches_batch_key UNIQUE (batch_key)
);

CREATE TABLE dealers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE TABLE dealer_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    product_model VARCHAR(64) NOT NULL,
    target_year INTEGER NOT NULL,
    target_month INTEGER NOT NULL,
    asktarget INTEGER,
    opportunity_won_count INTEGER NOT NULL,
    opportunity_create_count INTEGER NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE TABLE opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id VARCHAR(64) NOT NULL,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    product_model VARCHAR(64) NOT NULL,
    purchase_horizon VARCHAR(64) NOT NULL,
    stage_name VARCHAR(64) NOT NULL,
    lead_source VARCHAR(64) NOT NULL,
    created_date DATE NOT NULL,
    expected_close_date DATE,
    probability INTEGER NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id VARCHAR(64) NOT NULL,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    lead_source VARCHAR(64) NOT NULL,
    stage_name VARCHAR(64) NOT NULL,
    product_model VARCHAR(64) NOT NULL,
    created_date DATE,
    converted BOOLEAN NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE TABLE dealer_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    opportunity_id VARCHAR(64) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    status VARCHAR(64) NOT NULL,
    created_date DATE NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id VARCHAR(64) NOT NULL,
    campaign_name VARCHAR(256) NOT NULL,
    dealer_code VARCHAR(64) NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    dealer_group_name VARCHAR(128) NOT NULL,
    product_model VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    campaign_type VARCHAR(64) NOT NULL,
    created_date DATE NOT NULL,
    target_opportunity_amount INTEGER,
    actual_opportunity_count INTEGER,
    target_order_amount INTEGER,
    won_opportunity_count INTEGER,
    lead_count INTEGER,
    total_new_customer_target INTEGER,
    import_batch_id VARCHAR(64) NOT NULL
);

CREATE INDEX idx_import_batches_active_order
    ON import_batches (active, activated_at DESC, id DESC);

CREATE INDEX idx_dealers_import_batch
    ON dealers (import_batch_id);

CREATE INDEX idx_dealer_targets_import_batch
    ON dealer_targets (import_batch_id);

CREATE INDEX idx_opportunities_import_batch
    ON opportunities (import_batch_id);

CREATE INDEX idx_leads_import_batch
    ON leads (import_batch_id);

CREATE INDEX idx_dealer_tasks_import_batch
    ON dealer_tasks (import_batch_id);

CREATE INDEX idx_campaigns_import_batch
    ON campaigns (import_batch_id);

CREATE INDEX idx_dealers_batch_code
    ON dealers (import_batch_id, dealer_code);

CREATE INDEX idx_targets_batch_dealer
    ON dealer_targets (import_batch_id, dealer_code);

CREATE INDEX idx_opportunities_batch_business_id
    ON opportunities (import_batch_id, opportunity_id);

CREATE INDEX idx_leads_batch_business_id
    ON leads (import_batch_id, lead_id);

CREATE INDEX idx_tasks_batch_business_id
    ON dealer_tasks (import_batch_id, task_id);

CREATE INDEX idx_campaigns_batch_business_id
    ON campaigns (import_batch_id, campaign_id);
