CREATE TABLE auth_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    built_in BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_auth_roles_role_key UNIQUE (role_key)
);

CREATE TABLE auth_role_permissions (
    role_id BIGINT NOT NULL,
    permission_key VARCHAR(64) NOT NULL,
    PRIMARY KEY (role_id, permission_key),
    CONSTRAINT fk_auth_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES auth_roles (id)
);

CREATE TABLE auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    must_change_password BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_auth_users_username UNIQUE (username)
);

CREATE TABLE auth_user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_auth_user_roles_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id),
    CONSTRAINT fk_auth_user_roles_role
        FOREIGN KEY (role_id) REFERENCES auth_roles (id)
);

CREATE TABLE auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_key VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    access_token_hash VARCHAR(64) NOT NULL,
    refresh_token_hash VARCHAR(64) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    access_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    refresh_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rotated_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revocation_reason VARCHAR(64),
    version BIGINT NOT NULL,
    CONSTRAINT uq_auth_sessions_access_hash UNIQUE (access_token_hash),
    CONSTRAINT uq_auth_sessions_refresh_hash UNIQUE (refresh_token_hash),
    CONSTRAINT fk_auth_sessions_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id)
);

CREATE TABLE auth_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128),
    outcome VARCHAR(32) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    detail_code VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_auth_user_roles_role
    ON auth_user_roles (role_id, user_id);

CREATE INDEX idx_auth_sessions_family
    ON auth_sessions (family_key, issued_at);

CREATE INDEX idx_auth_sessions_user
    ON auth_sessions (user_id, revoked_at, refresh_expires_at);

CREATE INDEX idx_auth_audit_created
    ON auth_audit_events (created_at, id);

CREATE INDEX idx_auth_audit_actor
    ON auth_audit_events (actor_user_id, created_at);
