CREATE TABLE organization_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_key VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    node_type VARCHAR(32) NOT NULL,
    parent_id BIGINT,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_organization_nodes_key UNIQUE (node_key),
    CONSTRAINT fk_organization_nodes_parent
        FOREIGN KEY (parent_id) REFERENCES organization_nodes (id)
);

CREATE TABLE organization_dealer_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_node_id BIGINT NOT NULL,
    dealer_code VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_organization_dealer_mappings_code UNIQUE (dealer_code),
    CONSTRAINT fk_organization_dealer_mappings_node
        FOREIGN KEY (organization_node_id) REFERENCES organization_nodes (id)
);

CREATE TABLE organization_user_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    organization_node_id BIGINT NOT NULL,
    include_descendants BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_organization_user_grants UNIQUE (user_id, organization_node_id),
    CONSTRAINT fk_organization_user_grants_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id),
    CONSTRAINT fk_organization_user_grants_node
        FOREIGN KEY (organization_node_id) REFERENCES organization_nodes (id)
);

CREATE TABLE organization_role_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    organization_node_id BIGINT NOT NULL,
    include_descendants BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_organization_role_grants UNIQUE (role_id, organization_node_id),
    CONSTRAINT fk_organization_role_grants_role
        FOREIGN KEY (role_id) REFERENCES auth_roles (id),
    CONSTRAINT fk_organization_role_grants_node
        FOREIGN KEY (organization_node_id) REFERENCES organization_nodes (id)
);

CREATE INDEX idx_organization_nodes_parent
    ON organization_nodes (parent_id, id);

CREATE INDEX idx_organization_mappings_node
    ON organization_dealer_mappings (organization_node_id, dealer_code);

CREATE INDEX idx_organization_user_grants_user
    ON organization_user_grants (user_id, organization_node_id);

CREATE INDEX idx_organization_role_grants_role
    ON organization_role_grants (role_id, organization_node_id);

INSERT INTO organization_nodes (
    node_key,
    display_name,
    node_type,
    parent_id,
    enabled,
    created_at,
    updated_at,
    version
) VALUES (
    'GLOBAL_ROOT',
    'Global Dealer Organization',
    'GROUP',
    NULL,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
);

INSERT INTO auth_role_permissions (role_id, permission_key)
SELECT role.id, 'ORGANIZATION_READ'
FROM auth_roles role
WHERE role.role_key = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1
      FROM auth_role_permissions permission
      WHERE permission.role_id = role.id
        AND permission.permission_key = 'ORGANIZATION_READ'
  );

INSERT INTO auth_role_permissions (role_id, permission_key)
SELECT role.id, 'ORGANIZATION_MANAGE'
FROM auth_roles role
WHERE role.role_key = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1
      FROM auth_role_permissions permission
      WHERE permission.role_id = role.id
        AND permission.permission_key = 'ORGANIZATION_MANAGE'
  );

INSERT INTO auth_role_permissions (role_id, permission_key)
SELECT role.id, 'ORGANIZATION_GRANT_MANAGE'
FROM auth_roles role
WHERE role.role_key = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1
      FROM auth_role_permissions permission
      WHERE permission.role_id = role.id
        AND permission.permission_key = 'ORGANIZATION_GRANT_MANAGE'
  );
