CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_key VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_tenants_key UNIQUE (tenant_key)
);

INSERT INTO tenants (
    tenant_key, display_name, enabled, created_at, updated_at, version
) SELECT 'default', 'Default Tenant', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE tenant_key = 'default');

CREATE TABLE tenant_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_tenant_memberships_user_tenant UNIQUE (tenant_id, user_id),
    CONSTRAINT fk_tenant_memberships_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_tenant_memberships_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id)
);

CREATE TABLE tenant_membership_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uq_tenant_membership_roles UNIQUE (membership_id, role_id),
    CONSTRAINT fk_tenant_membership_roles_membership
        FOREIGN KEY (membership_id) REFERENCES tenant_memberships (id),
    CONSTRAINT fk_tenant_membership_roles_role
        FOREIGN KEY (role_id) REFERENCES auth_roles (id)
);

CREATE TABLE tenant_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    base_url VARCHAR(512) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    allowed_hosts VARCHAR(1024) NOT NULL,
    secret_ciphertext VARCHAR(2048) NOT NULL,
    secret_version INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_tenant_model_configs_tenant UNIQUE (tenant_id),
    CONSTRAINT fk_tenant_model_configs_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_tenant_model_configs_updated
    ON tenant_model_configs (tenant_id, updated_at);

ALTER TABLE import_batches ADD COLUMN tenant_id BIGINT;
ALTER TABLE dealers ADD COLUMN tenant_id BIGINT;
ALTER TABLE dealer_targets ADD COLUMN tenant_id BIGINT;
ALTER TABLE opportunities ADD COLUMN tenant_id BIGINT;
ALTER TABLE leads ADD COLUMN tenant_id BIGINT;
ALTER TABLE dealer_tasks ADD COLUMN tenant_id BIGINT;
ALTER TABLE campaigns ADD COLUMN tenant_id BIGINT;
ALTER TABLE organization_nodes ADD COLUMN tenant_id BIGINT;
ALTER TABLE organization_dealer_mappings ADD COLUMN tenant_id BIGINT;
ALTER TABLE organization_user_grants ADD COLUMN tenant_id BIGINT;
ALTER TABLE organization_role_grants ADD COLUMN tenant_id BIGINT;
ALTER TABLE auth_audit_events ADD COLUMN tenant_id BIGINT;

UPDATE import_batches SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE dealers SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE dealer_targets SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE opportunities SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE leads SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE dealer_tasks SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE campaigns SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE organization_nodes SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE organization_dealer_mappings SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE organization_user_grants SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;
UPDATE organization_role_grants SET tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default') WHERE tenant_id IS NULL;

ALTER TABLE import_batches ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE dealers ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE dealer_targets ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE opportunities ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE leads ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE dealer_tasks ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE campaigns ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE organization_nodes ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE organization_dealer_mappings ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE organization_user_grants ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE organization_role_grants ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE import_batches DROP CONSTRAINT IF EXISTS uq_import_batches_batch_key;
ALTER TABLE import_batches ADD CONSTRAINT uq_import_batches_tenant_batch_key
    UNIQUE (tenant_id, batch_key);

ALTER TABLE import_batches ADD CONSTRAINT fk_import_batches_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE dealers ADD CONSTRAINT fk_dealers_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE dealer_targets ADD CONSTRAINT fk_dealer_targets_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE opportunities ADD CONSTRAINT fk_opportunities_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE leads ADD CONSTRAINT fk_leads_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE dealer_tasks ADD CONSTRAINT fk_dealer_tasks_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE campaigns ADD CONSTRAINT fk_campaigns_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE organization_nodes ADD CONSTRAINT fk_organization_nodes_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE organization_dealer_mappings ADD CONSTRAINT fk_organization_mappings_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE organization_user_grants ADD CONSTRAINT fk_organization_user_grants_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE organization_role_grants ADD CONSTRAINT fk_organization_role_grants_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE auth_audit_events ADD CONSTRAINT fk_auth_audit_events_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE organization_nodes ADD CONSTRAINT uq_organization_nodes_tenant_id
    UNIQUE (tenant_id, id);
ALTER TABLE organization_nodes ADD CONSTRAINT fk_organization_nodes_parent_tenant
    FOREIGN KEY (tenant_id, parent_id) REFERENCES organization_nodes (tenant_id, id);
ALTER TABLE organization_dealer_mappings ADD CONSTRAINT fk_organization_mappings_node_tenant
    FOREIGN KEY (tenant_id, organization_node_id)
    REFERENCES organization_nodes (tenant_id, id);
ALTER TABLE organization_user_grants ADD CONSTRAINT fk_organization_user_grants_node_tenant
    FOREIGN KEY (tenant_id, organization_node_id)
    REFERENCES organization_nodes (tenant_id, id);
ALTER TABLE organization_role_grants ADD CONSTRAINT fk_organization_role_grants_node_tenant
    FOREIGN KEY (tenant_id, organization_node_id)
    REFERENCES organization_nodes (tenant_id, id);

INSERT INTO tenant_memberships (
    tenant_id, user_id, enabled, created_at, updated_at, version
)
SELECT default_tenant.id, user_row.id, user_row.enabled, user_row.created_at, user_row.updated_at, 0
FROM auth_users user_row
JOIN tenants default_tenant ON default_tenant.tenant_key = 'default'
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_memberships membership
    WHERE membership.tenant_id = default_tenant.id AND membership.user_id = user_row.id
);

INSERT INTO tenant_membership_roles (membership_id, role_id)
SELECT membership.id, user_role.role_id
FROM tenant_memberships membership
JOIN auth_user_roles user_role ON user_role.user_id = membership.user_id
WHERE membership.tenant_id = (SELECT id FROM tenants WHERE tenant_key = 'default')
  AND NOT EXISTS (
      SELECT 1
      FROM tenant_membership_roles membership_role
      WHERE membership_role.membership_id = membership.id
        AND membership_role.role_id = user_role.role_id
  );

ALTER TABLE organization_nodes DROP CONSTRAINT IF EXISTS uq_organization_nodes_key;
ALTER TABLE organization_dealer_mappings DROP CONSTRAINT IF EXISTS uq_organization_dealer_mappings_code;
ALTER TABLE organization_user_grants DROP CONSTRAINT IF EXISTS uq_organization_user_grants;
ALTER TABLE organization_role_grants DROP CONSTRAINT IF EXISTS uq_organization_role_grants;

ALTER TABLE organization_nodes ADD CONSTRAINT uq_organization_nodes_tenant_key
    UNIQUE (tenant_id, node_key);
ALTER TABLE organization_dealer_mappings ADD CONSTRAINT uq_organization_mappings_tenant_code
    UNIQUE (tenant_id, dealer_code);
ALTER TABLE organization_user_grants ADD CONSTRAINT uq_organization_user_grants_tenant
    UNIQUE (tenant_id, user_id, organization_node_id);
ALTER TABLE organization_role_grants ADD CONSTRAINT uq_organization_role_grants_tenant
    UNIQUE (tenant_id, role_id, organization_node_id);

DROP INDEX IF EXISTS idx_organization_nodes_parent;
CREATE INDEX idx_organization_nodes_parent
    ON organization_nodes (tenant_id, parent_id, id);
CREATE INDEX idx_organization_nodes_tenant
    ON organization_nodes (tenant_id, id);
CREATE INDEX idx_organization_mappings_tenant_node
    ON organization_dealer_mappings (tenant_id, organization_node_id, dealer_code);
CREATE INDEX idx_organization_user_grants_tenant_user
    ON organization_user_grants (tenant_id, user_id, organization_node_id);
CREATE INDEX idx_organization_role_grants_tenant_role
    ON organization_role_grants (tenant_id, role_id, organization_node_id);

CREATE INDEX idx_import_batches_tenant_active
    ON import_batches (tenant_id, active, activated_at DESC, id DESC);
CREATE INDEX idx_dealers_tenant_batch_code
    ON dealers (tenant_id, import_batch_id, dealer_code);
CREATE INDEX idx_dealer_targets_tenant_batch_dealer
    ON dealer_targets (tenant_id, import_batch_id, dealer_code);
CREATE INDEX idx_opportunities_tenant_batch_business_id
    ON opportunities (tenant_id, import_batch_id, opportunity_id);
CREATE INDEX idx_leads_tenant_batch_business_id
    ON leads (tenant_id, import_batch_id, lead_id);
CREATE INDEX idx_tasks_tenant_batch_business_id
    ON dealer_tasks (tenant_id, import_batch_id, task_id);
CREATE INDEX idx_campaigns_tenant_batch_business_id
    ON campaigns (tenant_id, import_batch_id, campaign_id);
CREATE INDEX idx_auth_audit_tenant
    ON auth_audit_events (tenant_id, created_at, id);
