CREATE TABLE report_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    creator_user_id BIGINT NOT NULL,
    report_type VARCHAR(16) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id VARCHAR(2048) NOT NULL,
    language VARCHAR(8) NOT NULL,
    topic VARCHAR(500) NOT NULL,
    schedule_kind VARCHAR(16) NOT NULL,
    local_time TIME NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    day_of_week INTEGER,
    day_of_month INTEGER,
    channel_key VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL,
    next_run_at TIMESTAMP WITH TIME ZONE,
    misfire_policy VARCHAR(16) NOT NULL,
    misfire_grace_minutes INTEGER NOT NULL,
    active_configuration_key VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL,
    CONSTRAINT uq_report_subscriptions_active_definition
        UNIQUE (tenant_id, creator_user_id, active_configuration_key),
    CONSTRAINT fk_report_subscriptions_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_subscriptions_creator
        FOREIGN KEY (creator_user_id) REFERENCES auth_users (id)
);

CREATE TABLE report_subscription_recipients (
    subscription_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    CONSTRAINT uq_report_subscription_recipients
        UNIQUE (subscription_id, recipient_user_id),
    CONSTRAINT fk_report_subscription_recipients_subscription
        FOREIGN KEY (subscription_id) REFERENCES report_subscriptions (id) ON DELETE CASCADE,
    CONSTRAINT fk_report_subscription_recipients_user
        FOREIGN KEY (recipient_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_subscriptions_owner
    ON report_subscriptions (tenant_id, creator_user_id, deleted_at, id);

CREATE INDEX idx_report_subscriptions_due
    ON report_subscriptions (tenant_id, enabled, next_run_at, id);

CREATE INDEX idx_report_subscription_recipients_user
    ON report_subscription_recipients (recipient_user_id, subscription_id);
