CREATE TABLE report_generation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    creator_user_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    report_type VARCHAR(16) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id VARCHAR(2048) NOT NULL,
    language VARCHAR(8) NOT NULL,
    topic VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    error_code VARCHAR(64),
    trace_id VARCHAR(128) NOT NULL,
    report_draft_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_report_generation_jobs_window
        UNIQUE (subscription_id, scheduled_at),
    CONSTRAINT uq_report_generation_jobs_idempotency
        UNIQUE (idempotency_key),
    CONSTRAINT fk_report_generation_jobs_subscription
        FOREIGN KEY (subscription_id) REFERENCES report_subscriptions (id),
    CONSTRAINT fk_report_generation_jobs_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_report_generation_jobs_creator
        FOREIGN KEY (creator_user_id) REFERENCES auth_users (id)
);

CREATE INDEX idx_report_generation_jobs_claim
    ON report_generation_jobs (status, next_retry_at, scheduled_at, id);

CREATE INDEX idx_report_generation_jobs_tenant
    ON report_generation_jobs (tenant_id, created_at, id);

CREATE INDEX idx_report_generation_jobs_subscription
    ON report_generation_jobs (subscription_id, scheduled_at);
