export const PERMISSION_KEYS = Object.freeze([
  "USER_READ",
  "USER_MANAGE",
  "ROLE_READ",
  "ROLE_MANAGE",
  "ORGANIZATION_READ",
  "ORGANIZATION_MANAGE",
  "ORGANIZATION_GRANT_MANAGE",
  "DASHBOARD_READ",
  "DATA_READ",
  "CHAT_USE",
  "KNOWLEDGE_QUERY",
  "REPORT_READ",
  "REPORT_GENERATE",
  "REPORT_COLLABORATE",
  "MODEL_CONFIG_TEST",
  "MODEL_USAGE_READ",
  "MODEL_USAGE_MANAGE",
  "MODEL_USAGE_PLATFORM_READ"
]);

export const ADMIN_READ_PERMISSIONS = Object.freeze([
  "USER_READ",
  "ROLE_READ",
  "ORGANIZATION_READ",
  "MODEL_USAGE_READ"
]);
